use super::Strings;

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "Update via WinGet";

pub(super) const STRINGS: Strings = Strings {
    window_title: "Claude Usage Tracker",
    refresh: "Refresh",
    update_frequency: "Update Frequency",
    one_minute: "1 Minute",
    five_minutes: "5 Minutes",
    fifteen_minutes: "15 Minutes",
    one_hour: "1 Hour",
    settings: "Settings",
    start_with_windows: "Start with Windows",
    reset_position: "Reset Position",
    language: "Language",
    system_default: "System Default",
    check_for_updates: "Check for Updates",
    checking_for_updates: "Checking for Updates...",
    updates: "Updates",
    update_in_progress: "An update check is already in progress.",
    up_to_date: "You already have the latest version.",
    up_to_date_short: "Up to date",
    update_failed: "Unable to update automatically",
    applying_update: "Applying update...",
    update_to: "Update to",
    update_available: "Update available",
    update_prompt_now: "Version {version} is available. Do you want to update now?",
    login_via_claude: "Login via Claude Code",
    not_logged_in: "Login",
    login_browser_opened: "Your browser has been opened to log in to Claude.\nAfter logging in, install Claude Code CLI to complete setup:\nnpm install -g @anthropic-ai/claude-code",
    login_in_progress: "Authentication is in progress...",
    exit: "Exit",
    session_window: "5h",
    weekly_window: "7d",
    now: "now",
    day_suffix: "d",
    hour_suffix: "h",
    minute_suffix: "m",
    second_suffix: "s",
};
